-- member-and-permission-management (B16): three-tier role model + guest policy
-- dial + role-change audit trail.
--
-- Phase 0 inventory (recorded 2026-04-19):
--   * `user.role` column already exists from 0002_add_admin_plugin_columns.sql
--     with values 'admin' / 'user' and default 'user'. We don't re-add it.
--   * The better-auth `admin()` plugin owns the `user` table (lives in
--     `hub:db`), so column/default edits happen at runtime via
--     `admin({ defaultRole: 'guest' })` in auth.config.ts (Phase 3). This
--     migration only performs the one-off data reconciliation.
--   * `mcp_tokens` has no user FK; B16 6.2.b needs one to evaluate
--     token-creator role × guest_policy at MCP entry.
--
-- Design references:
--   * openspec/changes/member-and-permission-management/design.md
--   * openspec/changes/member-and-permission-management/proposal.md
--
-- All four sections MUST run in the same migration so the post-migration
-- state is atomic: legacy `role='user'` is upgraded to `'member'` at the
-- same transaction boundary that introduces the settings / audit tables and
-- the new FK column. Running them separately risks a window where the app
-- observes only Admin + Guest (Member bucket empty).

PRAGMA foreign_keys = ON;

-- (a) Legacy user → member.
--
-- v0.x only used two roles: 'admin' (allowlist seed) and 'user' (any other
-- authenticated account). Under the three-tier model, the former `'user'`
-- semantics — "authenticated, non-admin, full Web / MCP access" — maps
-- exactly to `'member'`. Re-mapping here keeps existing active users at
-- full privilege instead of silently demoting them to Guest.
--
-- NOTE: New users created after this migration are defaulted to `'guest'`
-- by better-auth `admin({ defaultRole: 'guest' })` (Phase 3), not by any
-- DB-level default change; SQLite ALTER TABLE cannot edit column defaults
-- in place without a table rebuild, which we avoid here.
UPDATE user
SET role = 'member'
WHERE role = 'user';

-- (b) MCP token creator FK (Q1 = A).
--
-- Adds `created_by_user_id` so B16 6.2.b can resolve token → creator role
-- and consult `guest_policy`. Column is nullable: existing tokens stay NULL
-- and the MCP middleware treats NULL as `'admin'` (legacy system seed) to
-- preserve backward compatibility.
--
-- SQLite cannot add a FK via ALTER TABLE in some pragma combinations, but
-- `REFERENCES user(id)` parses and is enforced when `PRAGMA foreign_keys`
-- is ON (which the connection sets above). If future enforcement tightens,
-- a follow-up migration may need a table rebuild; for v1.0.0 this is fine.
ALTER TABLE mcp_tokens
  ADD COLUMN created_by_user_id TEXT REFERENCES user(id);

-- (c) System settings KV store + `guest_policy` seed.
--
-- Single-row-per-key table used as a lightweight settings surface. The
-- value column stores scalar strings; consumers (`getGuestPolicy`) parse
-- via the Zod schema in `shared/types/auth.ts` (`guestPolicySchema`) so
-- the enum constraint lives in the application layer, not the DB.
--
-- `updated_by` accepts:
--   * a better-auth `user.id` (admin who performed the change)
--   * the sentinel `'system'` (migrations / seed / fallback)
--   * the sentinel `'db-direct'` (manual SQL operator intervention)
-- (See design.md "Audit trail 的寫入策略" for the same sentinel family.)
CREATE TABLE IF NOT EXISTS system_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by TEXT NOT NULL
);

-- Seed guest_policy to its canonical default. `INSERT OR IGNORE` keeps the
-- migration idempotent: re-running it (e.g. after a staging rollback) does
-- not clobber a value an admin has since changed through the UI.
INSERT OR IGNORE INTO system_settings (key, value, updated_by)
VALUES ('guest_policy', 'same_as_member', 'system');

-- (d) Role-change audit trail.
--
-- Writer contract is enforced in code (`server/utils/member-role-changes.ts`
-- → `recordRoleChange`, B16 Q3=A "唯一入口"). This migration only creates
-- the table + lookup index; v1.0.0 has no read surface (admin-ui-post-core
-- will add one).
--
-- Column semantics:
--   id          — uuid v4 (generated by recordRoleChange)
--   user_id     — subject of the role change; FK to user(id)
--   from_role   — previous role snapshot ('admin'/'member'/'guest')
--   to_role     — new role snapshot (same domain)
--   changed_by  — actor; either a user.id or one of the sentinels listed
--                 in the system_settings comment above
--   reason      — optional free-text ("allowlist-seed", "admin-ui", …)
--   created_at  — ISO-8601 (stored as TEXT for consistency with the rest
--                 of the schema; CURRENT_TIMESTAMP returns that format)
--
-- The `(user_id, created_at)` composite index serves the dominant read
-- pattern ("all changes for this user, newest first") once admin UI reads
-- arrive in admin-ui-post-core.
CREATE TABLE IF NOT EXISTS member_role_changes (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  from_role TEXT NOT NULL,
  to_role TEXT NOT NULL,
  changed_by TEXT NOT NULL,
  reason TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE INDEX IF NOT EXISTS idx_member_role_changes_user_created
  ON member_role_changes(user_id, created_at);
